name: clinical_chemistry_mcqs
description: A Clinical Chemistry MCQs App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  
  # Hive for local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # For generating Hive adapters
  json_annotation: ^4.8.1
  
  # For state management
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  
  # For generating code
  json_serializable: ^6.7.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
